runtime: nodejs14
service: cleversehack-api
instance_class: B2
entrypoint: npm run start:prod
env: flex
manual_scaling:
  instances: 1
env_variables:
  DATABASE_CONNECTION_NAME: {{ DATABASE_CONNECTION_NAME }}
  NODE_ENV: production
  POSTGRES_USER: {{ POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ POSTGRES_DB }}
network:
  session_affinity: true
