runtime: nodejs14
service: cleversehack-api
instance_class: B2
entrypoint: npm run start:prod
manual_scaling:
  instances: 1
env_variables:
  DATABASE_CONNECTION_NAME: {{ DATABASE_CONNECTION_NAME }}
  NODE_ENV: production
