name: Deploy to App Engine
on:
  push:
    branches:
      - api-1.0
steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: "14"
  - run: brew install sd
  - run: |
      cd api
      yarn
      yarn build
  - uses: google-github-actions/deploy-appengine@v0.2.0
    with:
      deliverables: api/app.yml
      project_id: ${{ secrets.GCP_PROJECT }}
      credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      promote: true
      version: v1
